### ISSUE TITLE
No memusage, CPU, network data.

### ISSUE THREAD

**Issue by jfrag** [metanull-operator/eth2-grafana#1]
Hi, i don't have the node_memory_* queries in prometheus.

can you share your prometheus config file ?

**Comment by metanull-operator** [comment]
I will get you some more specific information later, but you'll want to install node_exporter. That software collects the CPU, memory, network stats and sends them along to prometheus. 

I'll be back in a few hours to give more details on the prometheus config.

**Comment by jfrag** [comment]
Thank's for the answer.

Found the solution.
Juste a few bug with network. I have changing the device param to eth0
