### ISSUE TITLE
Voluntary Exits

### ISSUE THREAD

**Issue by arobbins** [metanull-operator/eth2-grafana#11]
My dashboard recently updated the `Voluntary Exits Received` box (see screenshot below).

I did not initiate a validator exit on my end. Can someone tell me what this number is suppose to reflect?

Is it the number of voluntary exits _my validators have initiated_? Or is it tracking something else?

Thanks!

![Screen Shot 2022-07-13 at 4 48 33 PM](https://user-images.githubusercontent.com/961947/178842835-064430c2-7fae-4cc7-9332-f8d8c135a3f2.png)

**Comment by metanull-operator** [comment]
This should be voluntary exits across the entire network since your last start of Nimbus. I will confirm that and respond again if not.

**Comment by arobbins** [comment]
Ok thank you.
