### ISSUE TITLE
"Datasource dMBweH0Gz was not found"

### ISSUE THREAD

**Issue by CoeJoder** [metanull-operator/eth2-grafana#12]
Hi, I followed the guide and it's almost working.  But the panel "Total Validator Balance (USD)" is blank and I get the above error message in the browser console.  I'm not sure how to go about troubleshooting this issue.  I looked through the system logs for Grafana and Prometheus but could not find the error.  I would really appreciate any pointers on how to fix it.  Thank you

**Comment by CoeJoder** [comment]
Changing the query expression from `ethusd` to `ethusd{job="json"}` fixed the problem.  Not sure why; the original expression works fine on another node I'm running.

**Comment by metanull-operator** [comment]
Interesting. Thanks for the report. I'll look into whether a fix is needed.
