### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by fireheadman** [metanull-operator/eth2-grafana#7]
prysm v1.3.3 was just released and it now offers the version info to prometheus...
![image](https://user-images.githubusercontent.com/19847195/111357087-99276900-864e-11eb-8f9f-04716ec342fe.png)
![image](https://user-images.githubusercontent.com/19847195/111357215-bbb98200-864e-11eb-98df-edf09edc8287.png)

Wondering if you could incorporate a panel in the dashboard to show the beacon/validator version info?

**Comment by fireheadman** [comment]
![image](https://user-images.githubusercontent.com/19847195/111357359-dab81400-864e-11eb-9435-392702f0d735.png)

**Comment by metanull-operator** [comment]
This was added in my latest release a week or so ago.
